# Generated by Django 5.2.2 on 2025-07-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=30)),
                ('user_Email', models.EmailField(blank=True, max_length=60)),
                ('user_Number', models.IntegerField(blank=True)),
            ],
        ),
    ]
