# Generated by Django 5.2.2 on 2025-07-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_Number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
